// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// step1FMMrcpp
Rcpp::NumericVector step1FMMrcpp(const arma::colvec& alphaOmegaParameters, const arma::colvec& vData, const arma::colvec& timePoints);
RcppExport SEXP _FMM_step1FMMrcpp(SEXP alphaOmegaParametersSEXP, SEXP vDataSEXP, SEXP timePointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alphaOmegaParameters(alphaOmegaParametersSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type vData(vDataSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type timePoints(timePointsSEXP);
    rcpp_result_gen = Rcpp::wrap(step1FMMrcpp(alphaOmegaParameters, vData, timePoints));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FMM_step1FMMrcpp", (DL_FUNC) &_FMM_step1FMMrcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_FMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
