# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function: to estimate M, A and beta initial parameters also returns residual sum of squared (RSS).
#'
#' @param alphaOmegaParameters vector of the parameters alpha and omega.
#' @param vData: data to be fitted an FMM model.
#' @param timePoints: one single period time points.
#' @export
step1FMMrcpp <- function(alphaOmegaParameters, vData, timePoints) {
    .Call(`_FMM_step1FMMrcpp`, alphaOmegaParameters, vData, timePoints)
}

#' Internal function: to estimate M, A and beta initial parameters also returns residual sum of squared (RSS).
#'
#' @param alphaOmegaParameters vector of the parameters alpha and omega.
#' @param vData: data to be fitted an FMM model.
#' @param timePoints: one single period time points.
#' @export
step1FMMrcpp2 <- function(alphaOmegaParameters, vData, timePoints) {
    .Call(`_FMM_step1FMMrcpp2`, alphaOmegaParameters, vData, timePoints)
}

